/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowWeReviewRouteImport } from './routes/how-we-review'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OffersIndexRouteImport } from './routes/offers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OffersSlugRouteImport } from './routes/offers.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminOffersNewRouteImport } from './routes/admin.offers.new'
import { Route as AdminOffersSlugEditRouteImport } from './routes/admin.offers.$slug.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeReviewRoute = HowWeReviewRouteImport.update({
  id: '/how-we-review',
  path: '/how-we-review',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OffersSlugRoute = OffersSlugRouteImport.update({
  id: '/offers/$slug',
  path: '/offers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersNewRoute = AdminOffersNewRouteImport.update({
  id: '/offers/new',
  path: '/offers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersSlugEditRoute = AdminOffersSlugEditRouteImport.update({
  id: '/offers/$slug/edit',
  path: '/offers/$slug/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/how-we-review': typeof HowWeReviewRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/admin/offers/$slug/edit': typeof AdminOffersSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/how-we-review': typeof HowWeReviewRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/admin': typeof AdminIndexRoute
  '/offers': typeof OffersIndexRoute
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/admin/offers/$slug/edit': typeof AdminOffersSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/how-we-review': typeof HowWeReviewRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/admin/offers/$slug/edit': typeof AdminOffersSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/categories'
    | '/contact'
    | '/disclosure'
    | '/how-we-review'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/admin/login'
    | '/categories/$slug'
    | '/offers/$slug'
    | '/admin/'
    | '/offers/'
    | '/admin/offers/new'
    | '/admin/offers/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/categories'
    | '/contact'
    | '/disclosure'
    | '/how-we-review'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/admin/login'
    | '/categories/$slug'
    | '/offers/$slug'
    | '/admin'
    | '/offers'
    | '/admin/offers/new'
    | '/admin/offers/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/categories'
    | '/contact'
    | '/disclosure'
    | '/how-we-review'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/admin/login'
    | '/categories/$slug'
    | '/offers/$slug'
    | '/admin/'
    | '/offers/'
    | '/admin/offers/new'
    | '/admin/offers/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DisclosureRoute: typeof DisclosureRoute
  HowWeReviewRoute: typeof HowWeReviewRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  OffersSlugRoute: typeof OffersSlugRoute
  OffersIndexRoute: typeof OffersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-review': {
      id: '/how-we-review'
      path: '/how-we-review'
      fullPath: '/how-we-review'
      preLoaderRoute: typeof HowWeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/offers/$slug': {
      id: '/offers/$slug'
      path: '/offers/$slug'
      fullPath: '/offers/$slug'
      preLoaderRoute: typeof OffersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers/new': {
      id: '/admin/offers/new'
      path: '/offers/new'
      fullPath: '/admin/offers/new'
      preLoaderRoute: typeof AdminOffersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers/$slug/edit': {
      id: '/admin/offers/$slug/edit'
      path: '/offers/$slug/edit'
      fullPath: '/admin/offers/$slug/edit'
      preLoaderRoute: typeof AdminOffersSlugEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOffersNewRoute: typeof AdminOffersNewRoute
  AdminOffersSlugEditRoute: typeof AdminOffersSlugEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOffersNewRoute: AdminOffersNewRoute,
  AdminOffersSlugEditRoute: AdminOffersSlugEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactRoute: ContactRoute,
  DisclosureRoute: DisclosureRoute,
  HowWeReviewRoute: HowWeReviewRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  OffersSlugRoute: OffersSlugRoute,
  OffersIndexRoute: OffersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
